const char *vertexshader=
"attribute vec2 pos;\n"
"varying vec2 ftexcoord;\n" 
"uniform mat4 projection;\n"
"uniform vec4 texcoords;\n"
"uniform vec2 vector,size;\n"
"uniform float rot;\n"
"void main(){\n"
"mat4 model=mat4(1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,vector.x+(size.x/2.0),vector.y+(size.y/2.0),0.0,1.0);\n"
"mat4 rotation=mat4(cos(rot),-sin(rot),0.0,0.0,sin(rot),cos(rot),0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0);\n"
"gl_Position=projection*model*rotation*vec4(pos.x*size.x,pos.y*size.y,0.0,1.0);\n"
"if(pos.x<0.0&&pos.y<0.0)ftexcoord=vec2(texcoords[0],texcoords[3]);\n"
"else if(pos.x<0.0&&pos.y>0.0)ftexcoord=vec2(texcoords[0],texcoords[2]);\n"
"else if(pos.x>0.0&&pos.y<0.0)ftexcoord=vec2(texcoords[1],texcoords[3]);\n"
"else ftexcoord=vec2(texcoords[1],texcoords[2]);\n"
"}"
,*fragmentshader=
"uniform vec4 rgba;\n"
"uniform sampler2D tex;\n"
"varying vec2 ftexcoord;\n"
"void main(){\n"
"gl_FragColor=texture2D(tex,ftexcoord)*rgba;\n"
"}"
,*nightfragmentshader=
"uniform vec4 rgba;\n"
"uniform sampler2D tex;\n"
"varying vec2 ftexcoord;\n"
"void main(){\n"
"vec4 clr=texture2D(tex,ftexcoord)*rgba;\n"
"clr.r=1.0-clr.r;\n"
"clr.g=1.0-clr.g;\n"
"clr.b=1.0-clr.b;\n"
"gl_FragColor=clr;\n"
"}"
;